// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

#ifndef PROTOBUF_Data_2eproto__INCLUDED
#define PROTOBUF_Data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Data {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Data_2eproto();
void protobuf_AssignDesc_Data_2eproto();
void protobuf_ShutdownFile_Data_2eproto();

class Commodity;

// ===================================================================

class Commodity : public ::google::protobuf::Message {
 public:
  Commodity();
  virtual ~Commodity();

  Commodity(const Commodity& from);

  inline Commodity& operator=(const Commodity& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Commodity& default_instance();

  void Swap(Commodity* other);

  // implements Message ----------------------------------------------

  Commodity* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Commodity& from);
  void MergeFrom(const Commodity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required double price = 3;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 3;
  inline double price() const;
  inline void set_price(double value);

  // optional double discount = 4;
  inline bool has_discount() const;
  inline void clear_discount();
  static const int kDiscountFieldNumber = 4;
  inline double discount() const;
  inline void set_discount(double value);

  // optional string description = 5;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 5;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // @@protoc_insertion_point(class_scope:Data.Commodity)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_discount();
  inline void clear_has_discount();
  inline void set_has_description();
  inline void clear_has_description();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  double price_;
  double discount_;
  ::std::string* description_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_Data_2eproto();
  friend void protobuf_AssignDesc_Data_2eproto();
  friend void protobuf_ShutdownFile_Data_2eproto();

  void InitAsDefaultInstance();
  static Commodity* default_instance_;
};
// ===================================================================


// ===================================================================

// Commodity

// required string name = 1;
inline bool Commodity::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Commodity::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Commodity::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Commodity::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Commodity::name() const {
  return *name_;
}
inline void Commodity::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Commodity::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Commodity::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Commodity::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Commodity::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Commodity::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 id = 2;
inline bool Commodity::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Commodity::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Commodity::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Commodity::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Commodity::id() const {
  return id_;
}
inline void Commodity::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required double price = 3;
inline bool Commodity::has_price() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Commodity::set_has_price() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Commodity::clear_has_price() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Commodity::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline double Commodity::price() const {
  return price_;
}
inline void Commodity::set_price(double value) {
  set_has_price();
  price_ = value;
}

// optional double discount = 4;
inline bool Commodity::has_discount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Commodity::set_has_discount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Commodity::clear_has_discount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Commodity::clear_discount() {
  discount_ = 0;
  clear_has_discount();
}
inline double Commodity::discount() const {
  return discount_;
}
inline void Commodity::set_discount(double value) {
  set_has_discount();
  discount_ = value;
}

// optional string description = 5;
inline bool Commodity::has_description() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Commodity::set_has_description() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Commodity::clear_has_description() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Commodity::clear_description() {
  if (description_ != &::google::protobuf::internal::kEmptyString) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& Commodity::description() const {
  return *description_;
}
inline void Commodity::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Commodity::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Commodity::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Commodity::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    description_ = new ::std::string;
  }
  return description_;
}
inline ::std::string* Commodity::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Commodity::set_allocated_description(::std::string* description) {
  if (description_ != &::google::protobuf::internal::kEmptyString) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Data

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Data_2eproto__INCLUDED
